name: Trigger auto deployment for link-base-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/link-base-api-AutoDeployTrigger-5a5a85c5-539e-4bb9-8bb3-f63c705ce6a5.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LINKBASEAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io/kaiannn/link-base-api:main
          registryUsername: ${{ secrets.LINKBASEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LINKBASEAPI_REGISTRY_PASSWORD }}
          containerAppName: link-base-api
          resourceGroup: projects
          imageToBuild: docker.io/kaiannn/link-base-api:main/link-base-api:${{ github.sha }}
          

     

